-- ============================================
-- COSMOS NEWS - Seed de Notícias
-- Execute DEPOIS de criar um usuário no sistema
-- Altere o autor_id se necessário (padrão: 1)
-- ============================================

USE portal_astronomia;

INSERT INTO noticias (titulo, slug, resumo, noticia, categoria_id, autor_id, destaque, visualizacoes, created_at, updated_at) VALUES

-- DESTAQUE
('Telescópio James Webb captura imagem inédita de galáxia a 13 bilhões de anos-luz',
'telescopio-james-webb-captura-imagem-inedita-de-galaxia',
'A NASA revelou nesta semana uma das imagens mais impressionantes já registradas pelo telescópio espacial James Webb.',
'A NASA revelou nesta semana uma das imagens mais impressionantes já registradas pelo telescópio espacial James Webb: uma galáxia formada apenas 400 milhões de anos após o Big Bang, tornando-a uma das estruturas mais antigas já observadas pelo ser humano.\n\nA galáxia, catalogada como JADES-GS-z14-0, foi detectada através do instrumento NIRCam do telescópio, que opera no espectro infravermelho próximo. Os cientistas ficaram surpresos com o brilho e a complexidade da estrutura, que desafia modelos anteriores sobre a formação de galáxias no universo primitivo.\n\n\"Estamos literalmente olhando para o passado do universo\", afirmou a Dra. Christina Williams, pesquisadora principal do projeto. \"Esta descoberta muda completamente nossa compreensão sobre como as primeiras galáxias se formaram e evoluíram.\"\n\nO James Webb, lançado em dezembro de 2021, continua superando todas as expectativas da comunidade científica. Seu espelho primário de 6,5 metros de diâmetro permite captar luz extremamente fraca de objetos distantes, revelando detalhes nunca antes vistos.\n\nA equipe internacional de pesquisadores, composta por mais de 200 cientistas de 15 países, já está analisando os dados espectrográficos da galáxia para determinar sua composição química e taxa de formação estelar.',
5, 1, 1, 342, DATE_SUB(NOW(), INTERVAL 2 HOUR), DATE_SUB(NOW(), INTERVAL 2 HOUR)),

-- EXPLORAÇÃO ESPACIAL
('SpaceX anuncia missão tripulada a Marte para 2030 com nave Starship',
'spacex-anuncia-missao-tripulada-marte-2030',
'Elon Musk confirmou planos ambiciosos para enviar os primeiros humanos ao planeta vermelho até o final da década.',
'A SpaceX anunciou oficialmente seus planos para uma missão tripulada a Marte, prevista para 2030. A nave Starship, atualmente em fase avançada de testes, será o veículo responsável por transportar uma tripulação de 12 astronautas em uma jornada de aproximadamente 7 meses até o planeta vermelho.\n\nO plano inclui o envio prévio de naves cargueiras não tripuladas a partir de 2028, que levarão equipamentos, suprimentos e sistemas de suporte de vida para estabelecer uma base preliminar na superfície marciana.\n\n\"Marte não é apenas um destino, é o futuro da humanidade como espécie multiplanetária\", declarou Elon Musk durante a coletiva de imprensa realizada no complexo de Boca Chica, Texas.\n\nA Starship, com seus 120 metros de altura quando acoplada ao booster Super Heavy, é o maior e mais potente foguete já construído. Nos últimos testes orbitais, a nave demonstrou capacidade de reentrada atmosférica e pouso vertical com sucesso.\n\nA NASA já sinalizou interesse em colaborar com a missão, oferecendo suporte técnico e compartilhamento de dados coletados pelo rover Perseverance, que opera em Marte desde 2021.',
4, 1, 0, 287, DATE_SUB(NOW(), INTERVAL 5 HOUR), DATE_SUB(NOW(), INTERVAL 5 HOUR)),

-- PLANETAS
('Descoberto exoplaneta com atmosfera rica em vapor d\'água na zona habitável',
'descoberto-exoplaneta-atmosfera-vapor-dagua-zona-habitavel',
'Cientistas identificaram um mundo rochoso a 40 anos-luz que pode ter condições favoráveis à vida.',
'Uma equipe internacional de astrônomos descobriu um exoplaneta rochoso orbitando na zona habitável de sua estrela, com evidências claras de vapor d\'água em sua atmosfera. O planeta, denominado TOI-700 f, está localizado a aproximadamente 40 anos-luz da Terra, na constelação de Dorado.\n\nAs observações foram realizadas utilizando o Telescópio Espacial James Webb em conjunto com o satélite TESS da NASA. A análise espectroscópica revelou assinaturas inequívocas de H2O, além de traços de dióxido de carbono e metano.\n\n\"Esta é a primeira vez que detectamos água na atmosfera de um planeta rochoso na zona habitável\", explicou o Dr. José Rodriguez, astrofísico da Universidade de Cambridge. \"Isso não significa que encontramos vida, mas certamente encontramos um lugar onde ela poderia existir.\"\n\nO planeta tem aproximadamente 1,2 vezes o tamanho da Terra e completa uma órbita ao redor de sua estrela anã vermelha a cada 37 dias terrestres. Sua temperatura superficial estimada é de cerca de 15°C, compatível com a presença de água líquida.\n\nNovas observações estão programadas para os próximos meses, com foco na busca por biomarcadores como ozônio e fosfina.',
1, 1, 0, 198, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY)),

-- BURACOS NEGROS
('Astrônomos detectam maior buraco negro já registrado: 40 bilhões de massas solares',
'astronomos-detectam-maior-buraco-negro-ja-registrado',
'O objeto monstruoso está no centro de uma galáxia a 700 milhões de anos-luz e desafia teorias de formação.',
'Um grupo de pesquisadores do Observatório Europeu do Sul (ESO) anunciou a descoberta do maior buraco negro já catalogado pela ciência. Com uma massa estimada em 40 bilhões de vezes a do nosso Sol, o objeto ultramassivo está localizado no centro da galáxia Holm 15A, a cerca de 700 milhões de anos-luz da Terra.\n\nA descoberta foi possível graças a observações combinadas do Very Large Telescope (VLT) no Chile e do Event Horizon Telescope (EHT), a mesma rede de radiotelescópios que produziu a primeira imagem de um buraco negro em 2019.\n\n\"Para ter uma ideia da escala, o horizonte de eventos deste buraco negro é maior que todo o nosso sistema solar\", comparou a Dra. Elena Müller, líder do estudo. \"Se o colocássemos no lugar do Sol, ele engoliria tudo até além da órbita de Plutão.\"\n\nO buraco negro apresenta um disco de acreção extremamente luminoso, visível mesmo a distâncias cosmológicas. A energia emitida por esse disco é equivalente à luz de trilhões de estrelas combinadas.\n\nA descoberta levanta questões importantes sobre como buracos negros tão massivos puderam se formar. Os modelos atuais têm dificuldade em explicar o crescimento até essa escala, sugerindo que mecanismos ainda desconhecidos podem estar envolvidos.',
7, 1, 0, 256, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY)),

-- ESTRELAS
('Supernova visível a olho nu é registrada pela primeira vez em 400 anos',
'supernova-visivel-olho-nu-registrada-primeira-vez-400-anos',
'Estrela massiva na Via Láctea explodiu e pode ser observada no céu noturno durante as próximas semanas.',
'Pela primeira vez desde 1604, quando Johannes Kepler observou a famosa \"Stella Nova\", uma supernova na Via Láctea está visível a olho nu a partir da Terra. A estrela Betelgeuse, uma supergigante vermelha localizada na constelação de Órion a cerca de 650 anos-luz de distância, entrou em colapso gravitacional.\n\nO evento foi detectado inicialmente pelos observatórios LIGO e Virgo através de ondas gravitacionais, seguido por uma explosão de neutrinos registrada pelo detector IceCube na Antártida. Em poucas horas, o brilho da estrela aumentou dramaticamente, tornando-a o objeto mais brilhante no céu noturno depois da Lua.\n\n\"Este é literalmente o evento astronômico de nossas vidas\", declarou o professor Andrew Howell do Las Cumbres Observatory. \"Gerações de astrônomos sonharam em observar uma supernova galáctica com instrumentos modernos.\"\n\nA explosão ejetou camadas externas da estrela a velocidades superiores a 30.000 km/s, criando uma nebulosa em rápida expansão. Elementos pesados como ferro, ouro e urânio estão sendo sintetizados neste momento no interior da onda de choque.\n\nEspecialistas tranquilizam: apesar da proximidade cósmica, a distância de 650 anos-luz é segura para a Terra. Não há risco de radiação prejudicial.',
2, 1, 0, 445, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),

-- SISTEMA SOLAR
('Sonda Europa Clipper confirma oceano subterrâneo na lua de Júpiter',
'sonda-europa-clipper-confirma-oceano-subterraneo-lua-jupiter',
'Dados enviados pela sonda da NASA revelam um oceano global de água salgada sob a crosta de gelo de Europa.',
'A NASA confirmou uma das descobertas mais aguardadas da exploração espacial: a lua Europa de Júpiter possui um oceano global de água líquida salgada sob sua crosta de gelo. Os dados foram coletados pela sonda Europa Clipper, que realizou seu primeiro sobrevoo rasante a apenas 25 km da superfície.\n\nAs medições de radar e magnetometria revelaram que o oceano tem profundidade média de 100 km e contém aproximadamente o dobro do volume de água de todos os oceanos da Terra combinados. A crosta de gelo que o cobre tem entre 15 e 25 km de espessura.\n\n\"Os dados são inequívocos\", afirmou a Dra. Britney Schmidt, cientista planetária do Georgia Tech. \"Europa tem não apenas um oceano, mas um oceano quimicamente complexo, com sais, minerais e possivelmente fontes hidrotermais no fundo.\"\n\nA presença de fontes hidrotermais é particularmente empolgante porque, na Terra, esses ambientes sustentam ecossistemas inteiros independentes da luz solar. Bactérias extremófilas prosperam em condições semelhantes nas profundezas dos oceanos terrestres.\n\nA missão continuará realizando 49 sobrevoos de Europa nos próximos anos, cada um coletando dados mais detalhados sobre a composição do oceano e a possível existência de plumas de vapor d\'água jorrando através de fissuras no gelo.',
6, 1, 0, 178, DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY)),

-- ASTRONAUTAS
('Astronauta brasileiro é selecionado para missão na Estação Espacial Internacional',
'astronauta-brasileiro-selecionado-missao-estacao-espacial',
'Será a segunda vez que um brasileiro viaja ao espaço, 18 anos após a missão de Marcos Pontes em 2006.',
'A Agência Espacial Brasileira (AEB) anunciou que o tenente-coronel aviador Rafael Fernandes foi selecionado para integrar a tripulação da Expedição 78 da Estação Espacial Internacional (ISS), prevista para o segundo semestre do próximo ano.\n\nFernandes, de 38 anos, formado em Engenharia Aeroespacial pelo ITA e com mestrado em Astrofísica pela Universidade de São Paulo, foi escolhido entre mais de 2.000 candidatos em um processo seletivo que durou dois anos.\n\n\"Representar o Brasil no espaço é um sonho de infância que agora se torna realidade\", disse Fernandes emocionado durante a coletiva. \"Quero inspirar uma nova geração de jovens cientistas brasileiros.\"\n\nDurante sua estadia de 6 meses na ISS, o astronauta realizará experimentos desenvolvidos por universidades brasileiras, incluindo estudos sobre o comportamento de materiais em microgravidade e o cultivo de sementes de plantas nativas do cerrado em ambiente espacial.\n\nO treinamento está sendo realizado no Centro Espacial Johnson da NASA em Houston, Texas, e inclui simulações de caminhadas espaciais, operação de braços robóticos e procedimentos de emergência.\n\nA última vez que um brasileiro esteve no espaço foi em 2006, quando Marcos Pontes realizou uma missão de 10 dias a bordo da ISS.',
8, 1, 0, 312, DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY)),

-- TELESCÓPIOS
('Observatório Vera Rubin inicia operações e promete mapear todo o céu em 3 noites',
'observatorio-vera-rubin-inicia-operacoes',
'O maior telescópio de levantamento do mundo começou a capturar imagens com sua câmera de 3.2 gigapixels.',
'O Observatório Vera C. Rubin, localizado no Cerro Pachón no Chile, iniciou oficialmente suas operações científicas com a câmera digital mais poderosa já construída: um sensor de 3.2 gigapixels capaz de fotografar uma área do céu equivalente a 40 luas cheias em uma única exposição.\n\nO telescópio de 8.4 metros de diâmetro foi projetado para realizar o Legacy Survey of Space and Time (LSST), um levantamento que mapeará todo o céu visível a cada três noites durante dez anos consecutivos.\n\n\"O Vera Rubin vai produzir um filme do universo, não apenas fotografias\", explicou o diretor do observatório, Dr. Steven Kahn. \"Qualquer coisa que se mova, pisque ou exploda no céu, nós vamos detectar.\"\n\nEntre os objetivos científicos do projeto estão a catalogação de bilhões de galáxias, a detecção de milhões de asteroides potencialmente perigosos, o estudo da energia escura e da matéria escura, e a descoberta de fenômenos transitórios como supernovas e kilonovas.\n\nO volume de dados gerado será impressionante: cerca de 20 terabytes por noite de observação, totalizando mais de 60 petabytes ao longo da missão. Todos os dados serão disponibilizados publicamente para a comunidade científica global.\n\nO observatório recebeu o nome de Vera Rubin, astrônoma americana pioneira cujo trabalho sobre curvas de rotação galáctica forneceu evidências fundamentais para a existência da matéria escura.',
5, 1, 0, 156, DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY)),

-- GALÁXIAS
('Via Láctea está em rota de colisão com galáxia de Andrômeda, confirma novo estudo',
'via-lactea-rota-colisao-galaxia-andromeda',
'Simulações detalhadas mostram que a fusão começará em 4,5 bilhões de anos, formando uma galáxia elíptica gigante.',
'Um novo estudo publicado na revista Nature Astronomy utilizou dados do satélite Gaia da ESA para confirmar com precisão sem precedentes que a Via Láctea e a galáxia de Andrômeda (M31) estão em rota de colisão direta.\n\nAs medições mostram que Andrômeda está se aproximando a uma velocidade de 110 km/s, e o primeiro contato entre as duas galáxias ocorrerá em aproximadamente 4,5 bilhões de anos. A fusão completa levará cerca de 2 bilhões de anos adicionais, resultando em uma galáxia elíptica gigante que os pesquisadores já apelidaram de \"Milkdromeda\".\n\n\"Utilizamos os movimentos próprios de mais de 1.000 estrelas em Andrômeda para calcular a trajetória com uma margem de erro de apenas 5%\", explicou o Dr. Roeland van der Marel, do Space Telescope Science Institute.\n\nAs simulações computacionais mostram que, durante a fusão, as estrelas individuais dificilmente colidirão entre si devido às enormes distâncias que as separam. No entanto, as nuvens de gás serão comprimidas, desencadeando uma explosão de formação estelar que iluminará ambas as galáxias.\n\nO Sol e a Terra provavelmente sobreviverão ao evento, embora nosso sistema solar possa ser arremessado para uma órbita muito diferente dentro da nova galáxia.\n\nO estudo também revelou que a galáxia do Triângulo (M33) participará da fusão, sendo absorvida primeiro por Andrômeda antes do encontro com a Via Láctea.',
3, 1, 0, 203, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY)),

-- EXPLORAÇÃO ESPACIAL
('China conclui construção da primeira base permanente na Lua',
'china-conclui-construcao-primeira-base-permanente-lua',
'A estação lunar Tiangong-Yue pode abrigar até 6 astronautas e será usada para pesquisa e mineração.',
'A Agência Espacial Nacional da China (CNSA) anunciou a conclusão da primeira fase de construção da estação lunar Tiangong-Yue, localizada na borda da cratera Shackleton, próxima ao polo sul da Lua.\n\nA base consiste em três módulos pressurizados conectados, com capacidade para abrigar até 6 astronautas simultaneamente por períodos de até 6 meses. A estrutura inclui laboratórios científicos, áreas de habitação, um módulo de suporte de vida com sistema de reciclagem de água e ar, e painéis solares que aproveitam a iluminação quase constante disponível na região polar.\n\n\"Este é um marco na história da exploração espacial\", declarou o diretor da CNSA, Zhang Kejian. \"A humanidade agora tem um posto avançado permanente em outro mundo.\"\n\nOs módulos foram transportados por foguetes Long March 10 ao longo de cinco missões não tripuladas realizadas nos últimos dois anos. A montagem foi realizada de forma autônoma por robôs, com supervisão remota a partir da Terra.\n\nEntre os objetivos da base estão a pesquisa geológica lunar, testes de tecnologias para futuras missões a Marte, e a exploração de depósitos de gelo de água confirmados no interior de crateras permanentemente sombreadas.\n\nA primeira tripulação está prevista para chegar à base no próximo ano, em uma missão que também testará técnicas de extração de recursos lunares, como regolito para construção e oxigênio a partir do gelo.',
4, 1, 0, 267, DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY)),

-- BURACOS NEGROS
('Cientistas conseguem simular condições de um buraco negro em laboratório',
'cientistas-simulam-condicoes-buraco-negro-laboratorio',
'Experimento com átomos ultra-resfriados reproduziu o equivalente à radiação Hawking pela primeira vez.',
'Físicos da Universidade de Amsterdam conseguiram, pela primeira vez, reproduzir em laboratório condições análogas às encontradas próximas ao horizonte de eventos de um buraco negro. O experimento utilizou uma cadeia de átomos ultra-resfriados a temperaturas próximas do zero absoluto para simular a curvatura extrema do espaço-tempo.\n\nO resultado mais significativo foi a detecção de uma emissão térmica equivalente à radiação Hawking, um fenômeno teórico previsto por Stephen Hawking em 1974, mas nunca observado diretamente em um buraco negro real.\n\n\"Hawking previu que buracos negros não são completamente negros — eles emitem uma radiação fraca devido a efeitos quânticos\", explicou o Dr. Jeff Steinhauer, um dos autores do estudo. \"Nosso experimento é a confirmação experimental mais robusta dessa teoria até o momento.\"\n\nO dispositivo experimental consiste em uma fileira de 256 átomos de rubídio manipulados por feixes de laser. Ao alterar a facilidade com que os elétrons podiam \"saltar\" entre os átomos, os pesquisadores criaram um \"horizonte de eventos\" artificial.\n\nAlém de confirmar a teoria de Hawking, o experimento tem implicações profundas para a física teórica, particularmente para a busca de uma teoria quântica da gravidade — o \"Santo Graal\" da física moderna que unificaria a mecânica quântica e a relatividade geral.',
7, 1, 0, 189, DATE_SUB(NOW(), INTERVAL 7 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY)),

-- SISTEMA SOLAR
('Tempestade solar massiva causa aurora boreal visível até o sul do Brasil',
'tempestade-solar-massiva-causa-aurora-boreal-brasil',
'O evento geomagnético de classe G5 foi o mais intenso dos últimos 20 anos e gerou imagens espetaculares.',
'Uma tempestade solar de magnitude G5 — a mais alta na escala de intensidade — atingiu a Terra na madrugada de ontem, causando auroras boreais visíveis em latitudes incomumente baixas, incluindo estados do sul do Brasil como Rio Grande do Sul, Santa Catarina e Paraná.\n\nO evento foi causado por uma ejeção de massa coronal (CME) lançada pelo Sol três dias antes, viajando a uma velocidade de aproximadamente 2.500 km/s. Ao atingir o campo magnético terrestre, as partículas carregadas interagiram com a atmosfera superior, produzindo os espetaculares shows de luz.\n\nImagens compartilhadas nas redes sociais mostram céus tingidos de verde, roxo e vermelho em locais como Porto Alegre, Florianópolis e Curitiba. \"Nunca vi nada assim na vida\", relatou o fotógrafo Lucas Martins, que registrou o fenômeno na Serra Gaúcha.\n\nAlém do espetáculo visual, a tempestade causou interrupções em comunicações por rádio de alta frequência e forçou desvios de rotas aéreas polares por precaução. Alguns satélites de comunicação reportaram anomalias temporárias.\n\nEspecialistas alertam que o Sol está se aproximando do máximo de seu ciclo de 11 anos de atividade, e eventos semelhantes podem se repetir nos próximos meses. A recomendação é monitorar os alertas do NOAA Space Weather Prediction Center.',
6, 1, 0, 534, DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY)),

-- PLANETAS
('Anéis de Saturno estão desaparecendo mais rápido do que previsto, alerta estudo',
'aneis-saturno-estao-desaparecendo-mais-rapido',
'Novas medições indicam que os icônicos anéis podem desaparecer completamente em 100 milhões de anos.',
'Um estudo liderado por pesquisadores da Universidade de Indiana revelou que os anéis de Saturno estão perdendo massa a uma taxa significativamente maior do que estimativas anteriores sugeriam. Segundo os dados, os anéis podem desaparecer completamente dentro de 100 milhões de anos — metade do tempo previsto em estudos anteriores.\n\nA pesquisa utilizou dados da sonda Cassini, que operou no sistema de Saturno entre 2004 e 2017, combinados com observações recentes do James Webb. As análises mostram que partículas de gelo dos anéis estão sendo continuamente puxadas para a atmosfera do planeta pela gravidade e pela influência do campo magnético.\n\n\"Os anéis de Saturno estão chovendo sobre o planeta\", descreveu o Dr. James O\'Donoghue, autor principal do estudo. \"O material equivalente a uma piscina olímpica é drenado a cada 30 minutos.\"\n\nOs anéis, compostos principalmente por partículas de gelo de água com tamanhos variando de grãos de areia a blocos do tamanho de casas, são surpreendentemente jovens em termos cósmicos. Evidências sugerem que eles se formaram há apenas 100 a 400 milhões de anos, possivelmente pela destruição de uma lua gelada.\n\nIsso significa que vivemos em um período privilegiado da história do sistema solar para observar esse fenômeno. Os dinossauros, que viveram há 66 milhões de anos, teriam visto anéis ainda mais espetaculares do que os atuais.',
1, 1, 0, 167, DATE_SUB(NOW(), INTERVAL 9 DAY), DATE_SUB(NOW(), INTERVAL 9 DAY)),

-- GALÁXIAS
('Matéria escura pode ser composta por buracos negros primordiais, sugere nova teoria',
'materia-escura-buracos-negros-primordiais-nova-teoria',
'Pesquisadores propõem que buracos negros formados instantes após o Big Bang podem explicar a massa invisível do universo.',
'Uma equipe de físicos teóricos do MIT e da Universidade de Princeton publicou uma teoria revolucionária que propõe que a matéria escura — responsável por cerca de 27% da composição do universo — pode ser formada por buracos negros primordiais criados nos primeiros instantes após o Big Bang.\n\nDiferentemente dos buracos negros estelares formados pelo colapso de estrelas massivas, os buracos negros primordiais teriam se formado a partir de flutuações de densidade extremas no universo recém-nascido, quando ele tinha menos de um segundo de idade.\n\n\"Se nossa teoria estiver correta, ela resolve simultaneamente dois dos maiores mistérios da cosmologia: a natureza da matéria escura e a origem dos buracos negros supermassivos\", afirmou a Dra. Priyamvada Natarajan, coautora do estudo.\n\nO modelo prevê que esses buracos negros primordiais teriam massas na faixa de 10 a 100 vezes a massa do Sol, pequenos o suficiente para escapar à detecção direta até agora, mas numerosos o bastante para explicar os efeitos gravitacionais atribuídos à matéria escura.\n\nA teoria pode ser testada em breve. O detector de ondas gravitacionais LISA, previsto para lançamento pela ESA em 2035, teria sensibilidade suficiente para detectar fusões entre buracos negros primordiais, caso eles existam.\n\nO estudo já gerou intenso debate na comunidade científica, com alguns pesquisadores apontando possíveis conflitos com observações existentes de lentes gravitacionais.',
3, 1, 0, 145, DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),

-- ESTRELAS
('Descoberta estrela \"impossível\" que desafia leis da física conhecida',
'descoberta-estrela-impossivel-desafia-leis-fisica',
'Objeto estelar com massa 300 vezes maior que o Sol não deveria existir segundo modelos atuais.',
'Astrônomos utilizando o Very Large Telescope do ESO descobriram uma estrela na Grande Nuvem de Magalhães cuja massa estimada é de 300 vezes a do Sol — muito acima do limite teórico de 150 massas solares estabelecido por modelos de formação estelar.\n\nA estrela, denominada BAT99-98, foi observada com resolução sem precedentes graças ao sistema de óptica adaptativa MUSE. As medições confirmaram que se trata de um único objeto estelar, e não de um sistema binário ou múltiplo como se suspeitava anteriormente.\n\n\"Esta estrela simplesmente não deveria existir de acordo com nosso entendimento atual de como as estrelas se formam\", disse o Dr. Paul Crowther, da Universidade de Sheffield. \"Ela nos obriga a repensar os limites fundamentais da astrofísica estelar.\"\n\nCom uma luminosidade de mais de 6 milhões de vezes a do Sol e uma temperatura superficial de 45.000°C, BAT99-98 emite tanta energia que seus ventos estelares expelem matéria a velocidades de 3.000 km/s, perdendo massa equivalente à da Terra a cada mês.\n\nA estrela terá uma vida extremamente curta para os padrões cósmicos — apenas alguns milhões de anos — antes de explodir como uma hipernova, um evento ainda mais energético que uma supernova convencional, possivelmente deixando para trás um buraco negro de massa intermediária.',
2, 1, 0, 211, DATE_SUB(NOW(), INTERVAL 11 DAY), DATE_SUB(NOW(), INTERVAL 11 DAY)),

-- TELESCÓPIOS
('Radiotelescópio detecta sinal misterioso repetitivo vindo do centro da Via Láctea',
'radiotelescópio-detecta-sinal-misterioso-centro-via-lactea',
'O sinal não se encaixa em nenhum padrão conhecido de objetos astrofísicos e intriga a comunidade científica.',
'O radiotelescópio MeerKAT, localizado na África do Sul, detectou um sinal de rádio repetitivo e altamente polarizado proveniente da região central da Via Láctea que não se encaixa em nenhuma categoria conhecida de fonte astrofísica.\n\nO objeto, catalogado como ASKAP J173608.2-321635, emite pulsos de rádio irregulares que podem durar de minutos a horas, seguidos por períodos de silêncio que variam de semanas a meses. Quando ativo, o sinal é extremamente brilhante e apresenta uma polarização circular quase completa — uma característica rara em fontes de rádio naturais.\n\n\"Verificamos extensivamente se poderia ser interferência terrestre ou um artefato instrumental, e descartamos essas possibilidades\", afirmou a Dra. Ziteng Wang, da Universidade de Sydney. \"Este é um objeto real, e simplesmente não sabemos o que é.\"\n\nO sinal não corresponde a pulsares, magnetares, estrelas variáveis ou qualquer outro tipo conhecido de emissor de rádio. Sua localização próxima ao centro galáctico, uma região rica em fenômenos extremos, adiciona complexidade à investigação.\n\nA equipe está coordenando observações em múltiplos comprimentos de onda, incluindo raios-X e infravermelho, para tentar identificar uma contrapartida óptica do objeto. Enquanto isso, especulações vão desde um novo tipo de objeto astrofísico compacto até fenômenos associados ao buraco negro supermassivo Sagitário A*.',
5, 1, 0, 298, DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 12 DAY));
